/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Subscribe to trades (order executions) for a given asset type and currency.
 */
export type TradesAssetTypeCurrency = TradesAssetTypeCurrencyPubSubSchema;
/**
 * Asset type
 */
export type AssetType = 'erc20' | 'option' | 'perp';
/**
 * Currency
 */
export type Currency = string;
export type Method = string;
/**
 * Subscribed channel name
 */
export type Channel = string;
/**
 * Direction or the taker order
 */
export type Direction = 'buy' | 'sell';
/**
 * Index price of the underlying at the time of the trade
 */
export type IndexPrice = string;
/**
 * Instrument name
 */
export type InstrumentName = string;
/**
 * Mark price of the instrument at the time of the trade
 */
export type MarkPrice = string;
/**
 * Trade timestamp (in ms since Unix epoch)
 */
export type Timestamp = number;
/**
 * Amount filled in this trade
 */
export type TradeAmount = string;
/**
 * Trade ID
 */
export type TradeId = string;
/**
 * Price at which the trade was filled
 */
export type TradePrice = string;
export type Data = TradePublicResponseSchema[];

export interface TradesAssetTypeCurrencyPubSubSchema {
  channel_params: TradesAssetTypeCurrencyChannelSchema;
  notification: TradesAssetTypeCurrencyNotificationSchema;
}
export interface TradesAssetTypeCurrencyChannelSchema {
  asset_type: AssetType;
  currency: Currency;
}
export interface TradesAssetTypeCurrencyNotificationSchema {
  method: Method;
  params: TradesAssetTypeCurrencyNotificationParamsSchema;
}
export interface TradesAssetTypeCurrencyNotificationParamsSchema {
  channel: Channel;
  data: Data;
}
export interface TradePublicResponseSchema {
  direction: Direction;
  index_price: IndexPrice;
  instrument_name: InstrumentName;
  mark_price: MarkPrice;
  timestamp: Timestamp;
  trade_amount: TradeAmount;
  trade_id: TradeId;
  trade_price: TradePrice;
}
