/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type SpotFeedCurrency = SpotFeedCurrencyPubSubSchema;
/**
 * Currency
 */
export type Currency = string;
export type Method = string;
/**
 * Subscribed channel name
 */
export type Channel = string;
/**
 * Confidence levels of the price
 */
export type Confidence = string;
/**
 * Confidence levels of the price 24 hours ago
 */
export type ConfidencePrevDaily = string;
/**
 * Price of the currency
 */
export type Price = string;
/**
 * Price of the currency 24 hours ago
 */
export type PricePrevDaily = string;
/**
 * Unix timestamp of the price 24 hours ago
 */
export type TimestampPrevDaily = number;
/**
 * Timestamp of the spot feed snapshot
 */
export type Timestamp = number;

export interface SpotFeedCurrencyPubSubSchema {
  channel_params: SpotFeedCurrencyChannelSchema;
  notification: SpotFeedCurrencyNotificationSchema;
}
export interface SpotFeedCurrencyChannelSchema {
  currency: Currency;
}
export interface SpotFeedCurrencyNotificationSchema {
  method: Method;
  params: SpotFeedCurrencyNotificationParamsSchema;
}
export interface SpotFeedCurrencyNotificationParamsSchema {
  channel: Channel;
  data: SpotFeedCurrencyPublisherDataSchema;
}
export interface SpotFeedCurrencyPublisherDataSchema {
  feeds: Feeds;
  timestamp: Timestamp;
}
/**
 * Spot feed data
 */
export interface Feeds {
  [k: string]: SpotFeedSnapshotSchema;
}
export interface SpotFeedSnapshotSchema {
  confidence: Confidence;
  confidence_prev_daily: ConfidencePrevDaily;
  price: Price;
  price_prev_daily: PricePrevDaily;
  timestamp_prev_daily: TimestampPrevDaily;
}
