/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Internal RPC for creating a new notification.
 */
export type InternalCreateNotification = InternalCreateNotificationJSONRPCSchema;
export type Method = 'internal/create_notification';
/**
 * The specific event leading to the notification.
 */
export type Event = 'deposit' | 'withdraw' | 'transfer' | 'trade' | 'settlement' | 'liquidation' | 'custom';
export type SubaccountIds1 = number;
/**
 * A list of the subaccount_ids that were notified.
 */
export type SubaccountIds = SubaccountIds1[];

export interface InternalCreateNotificationJSONRPCSchema {
  request: InternalCreateNotificationRequestSchema;
  response: InternalCreateNotificationResponseSchema;
}
export interface InternalCreateNotificationRequestSchema {
  id?: string | number;
  method: Method;
  params: InternalCreateNotificationParamsSchema;
}
export interface InternalCreateNotificationParamsSchema {
  event: Event;
  event_details: EventDetails;
}
/**
 * A JSON-structured dictionary containing detailed data or context about the event.
 */
export interface EventDetails {
  [k: string]: any;
}
export interface InternalCreateNotificationResponseSchema {
  id: string | number;
  result: InternalCreateNotificationResultSchema;
}
export interface InternalCreateNotificationResultSchema {
  subaccount_ids: SubaccountIds;
}
