/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type InternalTriggerKeeper = InternalTriggerKeeperJSONRPCSchema;
export type Method = 'internal/trigger_keeper';
/**
 * ID of keeper to run
 */
export type Keeper = string;
/**
 * True if success
 */
export type Status = boolean;

export interface InternalTriggerKeeperJSONRPCSchema {
  request: InternalTriggerKeeperRequestSchema;
  response: InternalTriggerKeeperResponseSchema;
}
export interface InternalTriggerKeeperRequestSchema {
  id?: string | number;
  method: Method;
  params: InternalTriggerKeeperParamsSchema;
}
export interface InternalTriggerKeeperParamsSchema {
  keeper: Keeper;
}
export interface InternalTriggerKeeperResponseSchema {
  id: string | number;
  result: InternalTriggerKeeperResultSchema;
}
export interface InternalTriggerKeeperResultSchema {
  status: Status;
}
