/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Get all live instruments for which queues are expected to be running
 */
export type InternalGetAllLiveInstruments = InternalGetAllLiveInstrumentsJSONRPCSchema;
export type Method = 'internal/get_all_live_instruments';
export type Result1 = string;
export type Result = Result1[];

export interface InternalGetAllLiveInstrumentsJSONRPCSchema {
  request: InternalGetAllLiveInstrumentsRequestSchema;
  response: InternalGetAllLiveInstrumentsResponseSchema;
}
export interface InternalGetAllLiveInstrumentsRequestSchema {
  id?: string | number;
  method: Method;
  params: InternalGetAllLiveInstrumentsParamsSchema;
}
export interface InternalGetAllLiveInstrumentsParamsSchema {}
export interface InternalGetAllLiveInstrumentsResponseSchema {
  id: string | number;
  result: Result;
}
