/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Triggers a snapshot (For testing purposes)
 */
export type InternalTriggerSnapshot = InternalTriggerSnapshotJSONRPCSchema;
export type Method = "internal/trigger_snapshot";
/**
 * True if success
 */
export type Status = boolean;

export interface InternalTriggerSnapshotJSONRPCSchema {
  request: InternalTriggerSnapshotRequestSchema;
  response: InternalTriggerSnapshotResponseSchema;
}
export interface InternalTriggerSnapshotRequestSchema {
  id?: string | number;
  method: Method;
  params: InternalTriggerSnapshotParamsSchema;
}
export interface InternalTriggerSnapshotParamsSchema {}
export interface InternalTriggerSnapshotResponseSchema {
  id: string | number;
  result: InternalTriggerSnapshotResultSchema;
}
export interface InternalTriggerSnapshotResultSchema {
  status: Status;
}
