/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Internal Admin RPC for creating new module.
 */
export type InternalCreateModule = InternalCreateModuleJSONRPCSchema;
export type Method = "internal/create_module";
/**
 * On-chain address of the module contract
 */
export type Address = string;
/**
 * Module type
 */
export type ModuleType = "deposit" | "withdraw" | "trade" | "transfer" | "rm_change";
/**
 * On-chain address of the module contract
 */
export type Address1 = string;
/**
 * Module type
 */
export type ModuleType1 = "deposit" | "withdraw" | "trade" | "transfer" | "rm_change";
/**
 * `created`
 */
export type Status = string;

export interface InternalCreateModuleJSONRPCSchema {
  request: InternalCreateModuleRequestSchema;
  response: InternalCreateModuleResponseSchema;
}
export interface InternalCreateModuleRequestSchema {
  id?: string | number;
  method: Method;
  params: InternalCreateModuleParamsSchema;
}
export interface InternalCreateModuleParamsSchema {
  address: Address;
  module_type: ModuleType;
}
export interface InternalCreateModuleResponseSchema {
  id: string | number;
  result: InternalCreateModuleResultSchema;
}
export interface InternalCreateModuleResultSchema {
  address: Address1;
  module_type: ModuleType1;
  status: Status;
}
