/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Triggers an expiry sweep (For testing purposes)
 */
export type InternalTriggerRiskRunner = InternalTriggerRiskRunnerJSONRPCSchema;
export type Method = "internal/trigger_risk_runner";
/**
 * True if success
 */
export type Status = boolean;

export interface InternalTriggerRiskRunnerJSONRPCSchema {
  request: InternalTriggerRiskRunnerRequestSchema;
  response: InternalTriggerRiskRunnerResponseSchema;
}
export interface InternalTriggerRiskRunnerRequestSchema {
  id?: string | number;
  method: Method;
  params: InternalTriggerRiskRunnerParamsSchema;
}
export interface InternalTriggerRiskRunnerParamsSchema {}
export interface InternalTriggerRiskRunnerResponseSchema {
  id: string | number;
  result: InternalTriggerRiskRunnerResultSchema;
}
export interface InternalTriggerRiskRunnerResultSchema {
  status: Status;
}
