/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Fix balance drift for a given subaccount by completely resetting their balances to chain state
 */
export type InternalFixBalanceDrift = InternalFixBalanceDriftJSONRPCSchema;
export type Method = "internal/fix_balance_drift";
/**
 * Subaccount to fix balance drift for
 */
export type SubaccountIdToUpdate = number;
/**
 * Subaccount ID
 */
export type SubaccountId = number;
/**
 * Whether the balance drift was fixed
 */
export type Success = boolean;

export interface InternalFixBalanceDriftJSONRPCSchema {
  request: InternalFixBalanceDriftRequestSchema;
  response: InternalFixBalanceDriftResponseSchema;
}
export interface InternalFixBalanceDriftRequestSchema {
  id?: string | number;
  method: Method;
  params: InternalFixBalanceDriftParamsSchema;
}
export interface InternalFixBalanceDriftParamsSchema {
  subaccount_id_to_update: SubaccountIdToUpdate;
}
export interface InternalFixBalanceDriftResponseSchema {
  id: string | number;
  result: InternalFixBalanceDriftResultSchema;
}
export interface InternalFixBalanceDriftResultSchema {
  subaccount_id: SubaccountId;
  success: Success;
}
