/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Triggers an archive (For testing purposes)
 */
export type InternalTriggerDriftDetector = InternalTriggerDriftDetectorJSONRPCSchema;
export type Method = "internal/trigger_drift_detector";
/**
 * True if success
 */
export type Status = boolean;

export interface InternalTriggerDriftDetectorJSONRPCSchema {
  request: InternalTriggerDriftDetectorRequestSchema;
  response: InternalTriggerDriftDetectorResponseSchema;
}
export interface InternalTriggerDriftDetectorRequestSchema {
  id?: string | number;
  method: Method;
  params: InternalTriggerDriftDetectorParamsSchema;
}
export interface InternalTriggerDriftDetectorParamsSchema {}
export interface InternalTriggerDriftDetectorResponseSchema {
  id: string | number;
  result: InternalTriggerDriftDetectorResultSchema;
}
export interface InternalTriggerDriftDetectorResultSchema {
  status: Status;
}
