/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Historical Instrument data retriever that gets a particular instrument at a particular time
 */
export type InternalGetHistoricalInstrumentDataRaw = InternalGetHistoricalInstrumentDataRawJSONRPCSchema;
export type Method = 'internal/get_historical_instrument_data_raw';
/**
 * Instrument name
 */
export type Instrument = string;
/**
 * Interval of the snapshot
 */
export type Interval = number;
/**
 * Snapshot type (FIXED or RANDOM)
 */
export type SnapshotType = 'FIXED' | 'RANDOM';

export interface InternalGetHistoricalInstrumentDataRawJSONRPCSchema {
  request: InternalGetHistoricalInstrumentDataRawRequestSchema;
  response: InternalGetHistoricalInstrumentDataRawResponseSchema;
}
export interface InternalGetHistoricalInstrumentDataRawRequestSchema {
  id?: string | number;
  method: Method;
  params: InternalGetHistoricalInstrumentDataRawParamsSchema;
}
export interface InternalGetHistoricalInstrumentDataRawParamsSchema {
  instrument: Instrument;
  interval: Interval;
  snapshot_type: SnapshotType;
}
export interface InternalGetHistoricalInstrumentDataRawResponseSchema {
  id: string | number;
  result: InternalGetHistoricalInstrumentDataRawResultSchema;
}
export interface InternalGetHistoricalInstrumentDataRawResultSchema {
  data: Data;
}
/**
 * JSON data of the snapshot
 */
export interface Data {
  [k: string]: any;
}
