/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Triggers an archive (For testing purposes)
 */
export type InternalTriggerAccountsHistory = InternalTriggerAccountsHistoryJSONRPCSchema;
export type Method = "internal/trigger_accounts_history";
/**
 * True if success
 */
export type Status = boolean;

export interface InternalTriggerAccountsHistoryJSONRPCSchema {
  request: InternalTriggerAccountsHistoryRequestSchema;
  response: InternalTriggerAccountsHistoryResponseSchema;
}
export interface InternalTriggerAccountsHistoryRequestSchema {
  id?: string | number;
  method: Method;
  params: InternalTriggerAccountsHistoryParamsSchema;
}
export interface InternalTriggerAccountsHistoryParamsSchema {}
export interface InternalTriggerAccountsHistoryResponseSchema {
  id: string | number;
  result: InternalTriggerAccountsHistoryResultSchema;
}
export interface InternalTriggerAccountsHistoryResultSchema {
  status: Status;
}
