/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Fix balance drift for a given subaccounts by completely resetting their balances to chain state
 */
export type InternalFixMultipleBalanceDrift = InternalFixMultipleBalanceDriftJSONRPCSchema;
export type Method = "internal/fix_multiple_balance_drift";
export type SubaccountIdsToUpdate1 = number;
/**
 * Subaccounts to fix balance drift for
 */
export type SubaccountIdsToUpdate = SubaccountIdsToUpdate1[];
export type FailedUpdates1 = number;
/**
 * Subaccount IDs that failed to update
 */
export type FailedUpdates = FailedUpdates1[];
export type SuccesfulUpdates1 = number;
/**
 * Subaccount IDs that were updated
 */
export type SuccesfulUpdates = SuccesfulUpdates1[];

export interface InternalFixMultipleBalanceDriftJSONRPCSchema {
  request: InternalFixMultipleBalanceDriftRequestSchema;
  response: InternalFixMultipleBalanceDriftResponseSchema;
}
export interface InternalFixMultipleBalanceDriftRequestSchema {
  id?: string | number;
  method: Method;
  params: InternalFixMultipleBalanceDriftParamsSchema;
}
export interface InternalFixMultipleBalanceDriftParamsSchema {
  subaccount_ids_to_update: SubaccountIdsToUpdate;
}
export interface InternalFixMultipleBalanceDriftResponseSchema {
  id: string | number;
  result: InternalFixMultipleBalanceDriftResultSchema;
}
export interface InternalFixMultipleBalanceDriftResultSchema {
  failed_updates: FailedUpdates;
  succesful_updates: SuccesfulUpdates;
}
