/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type InternalNewLatch = InternalNewLatchJSONRPCSchema;
export type Method = 'internal/new_latch';
export type PodId = string;
export type ServiceType = string;
export type HeartbeatInterval = number;
export type InstrumentId = string;

export interface InternalNewLatchJSONRPCSchema {
  request: InternalNewLatchRequestSchema;
  response: InternalNewLatchResponseSchema;
}
export interface InternalNewLatchRequestSchema {
  id?: string | number;
  method: Method;
  params: InternalNewLatchParamsSchema;
}
export interface InternalNewLatchParamsSchema {
  pod_id: PodId;
  service_type: ServiceType;
}
export interface InternalNewLatchResponseSchema {
  id: string | number;
  result: InternalNewLatchResultSchema;
}
export interface InternalNewLatchResultSchema {
  heartbeat_interval: HeartbeatInterval;
  instrument_id: InstrumentId;
}
