/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Validate a list of channel names. Node server is expected to supply the
 * authenticated user's wallet address and/or subaccount ids.
 */
export type InternalValidateSubscribe = InternalValidateSubscribeJSONRPCSchema;
export type Method = "internal/validate_subscribe";
/**
 * A list of authenticated subaccount ids
 */
export type AuthSubaccountIds = AuthSubaccountIds1[] | null;
export type AuthSubaccountIds1 = number;
/**
 * The wallet address of the authenticated user
 */
export type AuthWallet = string | null;
export type Channels1 = string;
/**
 * A list of channels names to subscribe to
 */
export type Channels = Channels1[];
export type Status1 = string;

export interface InternalValidateSubscribeJSONRPCSchema {
  request: InternalValidateSubscribeRequestSchema;
  response: InternalValidateSubscribeResponseSchema;
}
export interface InternalValidateSubscribeRequestSchema {
  id?: string | number;
  method: Method;
  params: InternalValidateSubscribeParamsSchema;
}
export interface InternalValidateSubscribeParamsSchema {
  auth_subaccount_ids?: AuthSubaccountIds;
  auth_wallet?: AuthWallet;
  channels: Channels;
}
export interface InternalValidateSubscribeResponseSchema {
  id: string | number;
  result: InternalValidateSubscribeResultSchema;
}
export interface InternalValidateSubscribeResultSchema {
  status: Status;
}
/**
 * A mapping of `channel`&nbsp;&#11106;&nbsp;`status`.<br />Successful subscriptions will have status `ok`.<br />Failed subscriptions will contain an error message.
 */
export interface Status {
  [k: string]: Status1;
}
