/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Used by the Node server to cancel all of the user's orders on disconnect.
 */
export type InternalCancelOnDisconnect = InternalCancelOnDisconnectJSONRPCSchema;
export type Method = "internal/cancel_on_disconnect";
export type SubaccountIds1 = number;
/**
 * Subaccount IDs
 */
export type SubaccountIds = SubaccountIds1[];
/**
 * The result of this method call, `ok` if successful
 */
export type Result = "ok";

export interface InternalCancelOnDisconnectJSONRPCSchema {
  request: InternalCancelOnDisconnectRequestSchema;
  response: InternalCancelOnDisconnectResponseSchema;
}
export interface InternalCancelOnDisconnectRequestSchema {
  id?: string | number;
  method: Method;
  params: InternalCancelOnDisconnectParamsSchema;
}
export interface InternalCancelOnDisconnectParamsSchema {
  subaccount_ids: SubaccountIds;
}
export interface InternalCancelOnDisconnectResponseSchema {
  id: string | number;
  result: Result;
}
