/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Triggers an expiry sweep (For testing purposes)
 */
export type InternalTriggerExpirySweeper = InternalTriggerExpirySweeperJSONRPCSchema;
export type Method = "internal/trigger_expiry_sweeper";
/**
 * True if success
 */
export type Status = boolean;

export interface InternalTriggerExpirySweeperJSONRPCSchema {
  request: InternalTriggerExpirySweeperRequestSchema;
  response: InternalTriggerExpirySweeperResponseSchema;
}
export interface InternalTriggerExpirySweeperRequestSchema {
  id?: string | number;
  method: Method;
  params: InternalTriggerExpirySweeperParamsSchema;
}
export interface InternalTriggerExpirySweeperParamsSchema {}
export interface InternalTriggerExpirySweeperResponseSchema {
  id: string | number;
  result: InternalTriggerExpirySweeperResultSchema;
}
export interface InternalTriggerExpirySweeperResultSchema {
  status: Status;
}
