/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Snapshot Intervals Retriever that gets the intervals file from the S3 bucket
 */
export type InternalGetOrderSnapshotIntervals = InternalGetOrderSnapshotIntervalsJSONRPCSchema;
export type Method = 'internal/get_order_snapshot_intervals';
/**
 * Date of the snapshot for RANDOM snapshots
 */
export type Date = string | null;
/**
 * Instrument name
 */
export type Instrument = string;
/**
 * Snapshot type (FIXED or RANDOM)
 */
export type SnapshotType = 'FIXED' | 'RANDOM';
export type Intervals1 = number;
/**
 * List of snapshot intervals
 */
export type Intervals = Intervals1[];

export interface InternalGetOrderSnapshotIntervalsJSONRPCSchema {
  request: InternalGetOrderSnapshotIntervalsRequestSchema;
  response: InternalGetOrderSnapshotIntervalsResponseSchema;
}
export interface InternalGetOrderSnapshotIntervalsRequestSchema {
  id?: string | number;
  method: Method;
  params: InternalGetOrderSnapshotIntervalsParamsSchema;
}
export interface InternalGetOrderSnapshotIntervalsParamsSchema {
  date?: Date;
  instrument: Instrument;
  snapshot_type: SnapshotType;
}
export interface InternalGetOrderSnapshotIntervalsResponseSchema {
  id: string | number;
  result: InternalGetOrderSnapshotIntervalsResultSchema;
}
export interface InternalGetOrderSnapshotIntervalsResultSchema {
  intervals: Intervals;
}
