/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Used by the engine to evaluate a subaccounts open order risk after they are filled.
 */
export type InternalPostTradeRisk = InternalPostTradeRiskJSONRPCSchema;
export type Method = 'internal/post_trade_risk';
export type SubaccountId = number;
export type Success = boolean;

export interface InternalPostTradeRiskJSONRPCSchema {
  request: InternalPostTradeRiskRequestSchema;
  response: InternalPostTradeRiskResponseSchema;
}
export interface InternalPostTradeRiskRequestSchema {
  id?: string | number;
  method: Method;
  params: InternalPostTradeRiskParamsSchema;
}
export interface InternalPostTradeRiskParamsSchema {
  subaccount_id: SubaccountId;
}
export interface InternalPostTradeRiskResponseSchema {
  id: string | number;
  result: InternalPostTradeRiskResultSchema;
}
export interface InternalPostTradeRiskResultSchema {
  success: Success;
}
