/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Used for settling deposits to the blockchain by submitting them to the sequencer RPC.
 */
export type InternalSettleDeposit = InternalSettleDepositJSONRPCSchema;
export type Method = "internal/settle_deposit";
export type AssetId = string;
export type AssetName = string;
export type Amount = string;
export type Asset = string;
export type Decimals = number;
export type Manager = string;
export type Expiry = number;
export type Module = string;
export type Nonce = number;
export type Owner = string;
export type Signature = string;
export type Signer = string;
export type SubaccountId = number;
export type Status = 0 | 1 | 2;
export type TransactionHash = string | null;

export interface InternalSettleDepositJSONRPCSchema {
  request: InternalSettleDepositRequestSchema;
  response: InternalSettleDepositResponseSchema;
}
export interface InternalSettleDepositRequestSchema {
  id?: string | number;
  method: Method;
  params: InternalSettleDepositParamsSchema;
}
export interface InternalSettleDepositParamsSchema {
  asset_id: AssetId;
  asset_name: AssetName;
  data: DepositModuleDataSchema;
  expiry: Expiry;
  module: Module;
  nonce: Nonce;
  owner: Owner;
  signature: Signature;
  signer: Signer;
  subaccount_id: SubaccountId;
}
export interface DepositModuleDataSchema {
  amount: Amount;
  asset: Asset;
  decimals: Decimals;
  manager: Manager;
}
export interface InternalSettleDepositResponseSchema {
  id: string | number;
  result: InternalSettleDepositResultSchema;
}
export interface InternalSettleDepositResultSchema {
  status: Status;
  transaction_hash: TransactionHash;
}
