/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Cancel all open orders for a given subaccount.
 */
export type PrivateCancelAll = PrivateCancelAllJSONRPCSchema;
export type Method = 'private/cancel_all';
/**
 * Subaccount ID
 */
export type SubaccountId = number;
/**
 * Number of cancelled orders
 */
export type CancelledOrders = number;

export interface PrivateCancelAllJSONRPCSchema {
  request: PrivateCancelAllRequestSchema;
  response: PrivateCancelAllResponseSchema;
}
export interface PrivateCancelAllRequestSchema {
  id?: string | number;
  method: Method;
  params: PrivateCancelAllParamsSchema;
}
export interface PrivateCancelAllParamsSchema {
  subaccount_id: SubaccountId;
}
export interface PrivateCancelAllResponseSchema {
  id: string | number;
  result: PrivateCancelAllResultSchema;
}
export interface PrivateCancelAllResultSchema {
  cancelled_orders: CancelledOrders;
}
