/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resets (unfreezes) the mmp state for a subaccount (optionally filtered by currency)
 */
export type PrivateResetMmp = PrivateResetMmpJSONRPCSchema;
export type Method = 'private/reset_mmp';
/**
 * Currency to reset the mmp for. If not provided, resets all configs for the subaccount
 */
export type Currency = string | null;
/**
 * Subaccount_id for which to reset the mmp state
 */
export type SubaccountId = number;
/**
 * The result of this method call, `ok` if successful
 */
export type Result = 'ok';

export interface PrivateResetMmpJSONRPCSchema {
  request: PrivateResetMmpRequestSchema;
  response: PrivateResetMmpResponseSchema;
}
export interface PrivateResetMmpRequestSchema {
  id?: string | number;
  method: Method;
  params: PrivateResetMmpParamsSchema;
}
export interface PrivateResetMmpParamsSchema {
  currency?: Currency;
  subaccount_id: SubaccountId;
}
export interface PrivateResetMmpResponseSchema {
  id: string | number;
  result: Result;
}
