/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Get all subaccounts of an account / wallet
 */
export type PrivateGetSubaccounts = PrivateGetSubaccountsJSONRPCSchema;
export type Method = "private/get_subaccounts";
/**
 * Ethereum wallet address of account
 */
export type Wallet = string;
export type SubaccountIds1 = number;
/**
 * List of subaccount_ids owned by the wallet in `SubAccounts.sol`
 */
export type SubaccountIds = SubaccountIds1[];
/**
 * Ethereum wallet address
 */
export type Wallet1 = string;

export interface PrivateGetSubaccountsJSONRPCSchema {
  request: PrivateGetSubaccountsRequestSchema;
  response: PrivateGetSubaccountsResponseSchema;
}
export interface PrivateGetSubaccountsRequestSchema {
  id?: string | number;
  method: Method;
  params: PrivateGetSubaccountsParamsSchema;
}
export interface PrivateGetSubaccountsParamsSchema {
  wallet: Wallet;
}
export interface PrivateGetSubaccountsResponseSchema {
  id: string | number;
  result: PrivateGetSubaccountsResultSchema;
}
export interface PrivateGetSubaccountsResultSchema {
  subaccount_ids: SubaccountIds;
  wallet: Wallet1;
}
