/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * RPC to mark specified notifications as seen for a given subaccount.
 */
export type PrivateUpdateNotifications = PrivateUpdateNotificationsJSONRPCSchema;
export type Method = 'private/update_notifications';
export type NotificationIds1 = number;
/**
 * List of notification IDs to be marked as seen
 */
export type NotificationIds = NotificationIds1[];
/**
 * Status of the notification
 */
export type Status = 'unseen' | 'seen' | 'hidden';
/**
 * Subaccount_id
 */
export type SubaccountId = number;
/**
 * Number of notifications marked as seen
 */
export type UpdatedCount = number;

export interface PrivateUpdateNotificationsJSONRPCSchema {
  request: PrivateUpdateNotificationsRequestSchema;
  response: PrivateUpdateNotificationsResponseSchema;
}
export interface PrivateUpdateNotificationsRequestSchema {
  id?: string | number;
  method: Method;
  params: PrivateUpdateNotificationsParamsSchema;
}
export interface PrivateUpdateNotificationsParamsSchema {
  notification_ids: NotificationIds;
  status?: Status;
  subaccount_id: SubaccountId;
}
export interface PrivateUpdateNotificationsResponseSchema {
  id: string | number;
  result: PrivateUpdateNotificationsResultSchema;
}
export interface PrivateUpdateNotificationsResultSchema {
  updated_count: UpdatedCount;
}
