/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Get the notifications related to a subaccount.
 */
export type PrivateGetNotifications = PrivateGetNotificationsJSONRPCSchema;
export type Method = "private/get_notifications";
/**
 * Page number of results to return
 */
export type Page = number;
/**
 * Number of results per page
 */
export type PageSize = number;
/**
 * Status of the notification
 */
export type Status = ("unseen" | "seen" | "hidden") | null;
/**
 * Subaccount_id
 */
export type SubaccountId = number;
/**
 * Status of the notification
 */
export type Type = ("deposit" | "withdraw" | "transfer" | "trade" | "settlement" | "liquidation" | "custom") | null;
/**
 * The specific event leading to the notification.
 */
export type Event = string;
/**
 * The unique identifier for the notification.
 */
export type Id = number;
/**
 * The status of the notification, indicating if it has been read, pending, or processed.
 */
export type Status1 = string;
/**
 * The subaccount_id associated with the notification.
 */
export type SubaccountId1 = number;
/**
 * The timestamp indicating when the notification was created or triggered.
 */
export type Timestamp = number;
/**
 * The transaction id associated with the notification.
 */
export type TransactionId = number | null;
/**
 * The transaction hash associated with the notification.
 */
export type TxHash = string | null;
/**
 * Notification response
 */
export type Notifications = NotificationResponseSchema[];
/**
 * Subaccount_id
 */
export type SubaccountId2 = number;

export interface PrivateGetNotificationsJSONRPCSchema {
  request: PrivateGetNotificationsRequestSchema;
  response: PrivateGetNotificationsResponseSchema;
}
export interface PrivateGetNotificationsRequestSchema {
  id?: string | number;
  method: Method;
  params: PrivateGetNotificationsParamsSchema;
}
export interface PrivateGetNotificationsParamsSchema {
  page?: Page;
  page_size?: PageSize;
  status?: Status;
  subaccount_id: SubaccountId;
  type?: Type;
}
export interface PrivateGetNotificationsResponseSchema {
  id: string | number;
  result: PrivateGetNotificationsResultSchema;
}
export interface PrivateGetNotificationsResultSchema {
  notifications: Notifications;
  subaccount_id: SubaccountId2;
}
export interface NotificationResponseSchema {
  event: Event;
  event_details: EventDetails;
  id: Id;
  status: Status1;
  subaccount_id: SubaccountId1;
  timestamp: Timestamp;
  transaction_id?: TransactionId;
  tx_hash?: TxHash;
}
/**
 * A JSON-structured dictionary containing detailed data or context about the event.
 */
export interface EventDetails {
  [k: string]: any;
}
