/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Get collaterals of a subaccount
 */
export type PrivateGetCollaterals = PrivateGetCollateralsJSONRPCSchema;
export type Method = 'private/get_collaterals';
/**
 * Subaccount_id
 */
export type SubaccountId = number;
/**
 * Asset amount of given collateral
 */
export type Amount = string;
/**
 * Asset name
 */
export type AssetName = string;
/**
 * `erc20`, `option`, or `perp`
 */
export type AssetType = 'erc20' | 'option' | 'perp';
/**
 * Cumulative interest earned on supplying collateral or paid for borrowing
 */
export type CumulativeInterest = string;
/**
 * Underlying currency of asset (`ETH`, `BTC`, etc)
 */
export type Currency = string;
/**
 * USD value of collateral that contributes to initial margin
 */
export type InitialMargin = string;
/**
 * USD value of collateral that contributes to maintenance margin
 */
export type MaintenanceMargin = string;
/**
 * Current mark price of the asset
 */
export type MarkPrice = string;
/**
 * USD value of the collateral (amount * mark price)
 */
export type MarkValue = string;
/**
 * Portion of interest that has not yet been settled on-chain. This number is added to the portfolio value for margin calculations purposes.
 */
export type PendingInterest = string;
/**
 * All collaterals that count towards margin of subaccount
 */
export type Collaterals = CollateralResponseSchema[];
/**
 * Subaccount_id
 */
export type SubaccountId1 = number;

export interface PrivateGetCollateralsJSONRPCSchema {
  request: PrivateGetCollateralsRequestSchema;
  response: PrivateGetCollateralsResponseSchema;
}
export interface PrivateGetCollateralsRequestSchema {
  id?: string | number;
  method: Method;
  params: PrivateGetCollateralsParamsSchema;
}
export interface PrivateGetCollateralsParamsSchema {
  subaccount_id: SubaccountId;
}
export interface PrivateGetCollateralsResponseSchema {
  id: string | number;
  result: PrivateGetCollateralsResultSchema;
}
export interface PrivateGetCollateralsResultSchema {
  collaterals: Collaterals;
  subaccount_id: SubaccountId1;
}
export interface CollateralResponseSchema {
  amount: Amount;
  asset_name: AssetName;
  asset_type: AssetType;
  cumulative_interest: CumulativeInterest;
  currency: Currency;
  initial_margin: InitialMargin;
  maintenance_margin: MaintenanceMargin;
  mark_price: MarkPrice;
  mark_value: MarkValue;
  pending_interest: PendingInterest;
}
