/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Withdraw an asset to wallet.
 */
export type PrivateWithdraw = PrivateWithdrawJSONRPCSchema;
export type Method = "private/withdraw";
/**
 * Amount of the asset to withdraw
 */
export type Amount = string;
/**
 * Name of asset to withdraw
 */
export type AssetName = string;
/**
 * Unique nonce defined as <UTC_timestamp in ms><random_number_up_to_6_digits> (e.g. 1695836058725001, where 001 is the random number)
 */
export type Nonce = number;
/**
 * Ethereum signature of the withdraw
 */
export type Signature = string;
/**
 * Unix timestamp in seconds. Expiry MUST be >5min from now
 */
export type SignatureExpirySec = number;
/**
 * Ethereum wallet address that is signing the withdraw
 */
export type Signer = string;
/**
 * Subaccount_id
 */
export type SubaccountId = number;
/**
 * `requested`
 */
export type Status = string;
/**
 * Transaction id of the withdrawal
 */
export type TransactionId = string;

export interface PrivateWithdrawJSONRPCSchema {
  request: PrivateWithdrawRequestSchema;
  response: PrivateWithdrawResponseSchema;
}
export interface PrivateWithdrawRequestSchema {
  id?: string | number;
  method: Method;
  params: PrivateWithdrawParamsSchema;
}
export interface PrivateWithdrawParamsSchema {
  amount: Amount;
  asset_name: AssetName;
  nonce: Nonce;
  signature: Signature;
  signature_expiry_sec: SignatureExpirySec;
  signer: Signer;
  subaccount_id: SubaccountId;
}
export interface PrivateWithdrawResponseSchema {
  id: string | number;
  result: PrivateWithdrawResultSchema;
}
export interface PrivateWithdrawResultSchema {
  status: Status;
  transaction_id: TransactionId;
}
