/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Enables cancel on disconnect for the account
 */
export type PrivateSetCancelOnDisconnect = PrivateSetCancelOnDisconnectJSONRPCSchema;
export type Method = 'private/set_cancel_on_disconnect';
/**
 * Whether to enable or disable cancel on disconnect
 */
export type Enabled = boolean;
/**
 * Public key (wallet) of the account
 */
export type Wallet = string;
export type Result = 'ok';

export interface PrivateSetCancelOnDisconnectJSONRPCSchema {
  request: PrivateSetCancelOnDisconnectRequestSchema;
  response: PrivateSetCancelOnDisconnectResponseSchema;
}
export interface PrivateSetCancelOnDisconnectRequestSchema {
  id?: string | number;
  method: Method;
  params: PrivateSetCancelOnDisconnectParamsSchema;
}
export interface PrivateSetCancelOnDisconnectParamsSchema {
  enabled: Enabled;
  wallet: Wallet;
}
export interface PrivateSetCancelOnDisconnectResponseSchema {
  id: string | number;
  result: Result;
}
