/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type PrivateSessionKeys = PrivateSessionKeysJSONRPCSchema;
export type Method = "private/session_keys";
/**
 * Ethereum wallet address of account
 */
export type Wallet = string;
/**
 * Session key expiry timestamp in sec
 */
export type ExpirySec = number;
/**
 * User-defined session key label
 */
export type Label = string;
/**
 * Public session key address (Ethereum EOA)
 */
export type PublicSessionKey = string;
/**
 * List of session keys (includes unactivated and expired keys)
 */
export type PublicSessionKeys = SessionKeyResponseSchema[];

export interface PrivateSessionKeysJSONRPCSchema {
  request: PrivateSessionKeysRequestSchema;
  response: PrivateSessionKeysResponseSchema;
}
export interface PrivateSessionKeysRequestSchema {
  id?: string | number;
  method: Method;
  params: PrivateSessionKeysParamsSchema;
}
export interface PrivateSessionKeysParamsSchema {
  wallet: Wallet;
}
export interface PrivateSessionKeysResponseSchema {
  id: string | number;
  result: PrivateSessionKeysResultSchema;
}
export interface PrivateSessionKeysResultSchema {
  public_session_keys: PublicSessionKeys;
}
export interface SessionKeyResponseSchema {
  expiry_sec: ExpirySec;
  label?: Label;
  public_session_key: PublicSessionKey;
}
