/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Deposit an asset to a subaccount.
 */
export type PrivateDeposit = PrivateDepositJSONRPCSchema;
export type Method = "private/deposit";
/**
 * Amount of the asset to deposit
 */
export type Amount = string;
/**
 * Name of asset to deposit
 */
export type AssetName = string;
/**
 * Unique nonce defined as <UTC_timestamp in ms><random_number_up_to_6_digits> (e.g. 1695836058725001, where 001 is the random number)
 */
export type Nonce = number;
/**
 * Ethereum signature of the deposit
 */
export type Signature = string;
/**
 * Unix timestamp in seconds. Expiry MUST be >5min from now
 */
export type SignatureExpirySec = number;
/**
 * Ethereum wallet address that is signing the deposit
 */
export type Signer = string;
/**
 * Subaccount_id
 */
export type SubaccountId = number;
/**
 * `requested`
 */
export type Status = string;
/**
 * Transaction id of the deposit
 */
export type TransactionId = string;

export interface PrivateDepositJSONRPCSchema {
  request: PrivateDepositRequestSchema;
  response: PrivateDepositResponseSchema;
}
export interface PrivateDepositRequestSchema {
  id?: string | number;
  method: Method;
  params: PrivateDepositParamsSchema;
}
export interface PrivateDepositParamsSchema {
  amount: Amount;
  asset_name: AssetName;
  nonce: Nonce;
  signature: Signature;
  signature_expiry_sec: SignatureExpirySec;
  signer: Signer;
  subaccount_id: SubaccountId;
}
export interface PrivateDepositResponseSchema {
  id: string | number;
  result: PrivateDepositResultSchema;
}
export interface PrivateDepositResultSchema {
  status: Status;
  transaction_id: TransactionId;
}
