/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Account details getter
 */
export type PrivateGetAccount = PrivateGetAccountJSONRPCSchema;
export type Method = 'private/get_account';
/**
 * Ethereum wallet address of account
 */
export type Wallet = string;
/**
 * Whether cancel on disconnect is enabled for the account
 */
export type CancelOnDisconnect = boolean;
export type SubaccountIds1 = number;
/**
 * List of subaccount_ids owned by the wallet in `SubAccounts.sol`
 */
export type SubaccountIds = SubaccountIds1[];
/**
 * Ethereum wallet address
 */
export type Wallet1 = string;
/**
 * Max transactions per second for matching requests over websocket (see `Rate Limiting` in docs)
 */
export type WebsocketMatchingTps = number;
/**
 * Max transactions per second for non-matching requests over websocket (see `Rate Limiting` in docs)
 */
export type WebsocketNonMatchingTps = number;

export interface PrivateGetAccountJSONRPCSchema {
  request: PrivateGetAccountRequestSchema;
  response: PrivateGetAccountResponseSchema;
}
export interface PrivateGetAccountRequestSchema {
  id?: string | number;
  method: Method;
  params: PrivateGetAccountParamsSchema;
}
export interface PrivateGetAccountParamsSchema {
  wallet: Wallet;
}
export interface PrivateGetAccountResponseSchema {
  id: string | number;
  result: PrivateGetAccountResultSchema;
}
export interface PrivateGetAccountResultSchema {
  cancel_on_disconnect: CancelOnDisconnect;
  subaccount_ids: SubaccountIds;
  wallet: Wallet1;
  websocket_matching_tps: WebsocketMatchingTps;
  websocket_non_matching_tps: WebsocketNonMatchingTps;
}
