/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Generate a list of URLs to retrieve archived orders
 */
export type PrivateExpiredAndCancelledHistory = PrivateExpiredAndCancelledHistoryJSONRPCSchema;
export type Method = "private/expired_and_cancelled_history";
/**
 * End Unix timestamp
 */
export type EndTimestamp = number;
/**
 * Expiry of download link in seconds. Maximum of 604800.
 */
export type Expiry = number;
/**
 * Start Unix timestamp
 */
export type StartTimestamp = number;
/**
 * Subaccount to download data for
 */
export type SubaccountId = number;
/**
 * Wallet to download data for
 */
export type Wallet = string;
export type PresignedUrls1 = string;
/**
 * List of presigned URLs to the snapshots
 */
export type PresignedUrls = PresignedUrls1[];

export interface PrivateExpiredAndCancelledHistoryJSONRPCSchema {
  request: PrivateExpiredAndCancelledHistoryRequestSchema;
  response: PrivateExpiredAndCancelledHistoryResponseSchema;
}
export interface PrivateExpiredAndCancelledHistoryRequestSchema {
  id?: string | number;
  method: Method;
  params: PrivateExpiredAndCancelledHistoryParamsSchema;
}
export interface PrivateExpiredAndCancelledHistoryParamsSchema {
  end_timestamp: EndTimestamp;
  expiry: Expiry;
  start_timestamp: StartTimestamp;
  subaccount_id: SubaccountId;
  wallet: Wallet;
}
export interface PrivateExpiredAndCancelledHistoryResponseSchema {
  id: string | number;
  result: PrivateExpiredAndCancelledHistoryResultSchema;
}
export interface PrivateExpiredAndCancelledHistoryResultSchema {
  presigned_urls: PresignedUrls;
}
