/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Get the TWAPs for the perp mid price, ask impact price, and bid impact price
 */
export type PublicGetPerpImpactTwap = PublicGetPerpImpactTwapJSONRPCSchema;
export type Method = "public/get_perp_impact_twap";
/**
 * Currency
 */
export type Currency = string | null;
/**
 * End time
 */
export type EndTime = number | null;
/**
 * Start time
 */
export type StartTime = number | null;
/**
 * TWAP of the difference of ask impact price and spot price
 */
export type AskImpactDiffTwap = string;
/**
 * TWAP of the difference of bid impact price and spot price
 */
export type BidImpactDiffTwap = string;
/**
 * Currency
 */
export type Currency1 = string;
/**
 * TWAP of the difference of mid price and spot price
 */
export type MidPriceDiffTwap = string;

export interface PublicGetPerpImpactTwapJSONRPCSchema {
  request: PublicGetPerpImpactTwapRequestSchema;
  response: PublicGetPerpImpactTwapResponseSchema;
}
export interface PublicGetPerpImpactTwapRequestSchema {
  id?: string | number;
  method: Method;
  params: PublicGetPerpImpactTwapParamsSchema;
}
export interface PublicGetPerpImpactTwapParamsSchema {
  currency: Currency;
  end_time: EndTime;
  start_time: StartTime;
}
export interface PublicGetPerpImpactTwapResponseSchema {
  id: string | number;
  result: PublicGetPerpImpactTwapResultSchema;
}
export interface PublicGetPerpImpactTwapResultSchema {
  ask_impact_diff_twap: AskImpactDiffTwap;
  bid_impact_diff_twap: BidImpactDiffTwap;
  currency: Currency1;
  mid_price_diff_twap: MidPriceDiffTwap;
}
