/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Get the value history of a subaccount
 */
export type PublicChangeComplianceStatus = PublicChangeComplianceStatusJSONRPCSchema;
export type Method = 'public/change_compliance_status';
/**
 * Compliance status enum: enabled, disabled, force_enabled, force_disabled
 */
export type Status = 'enabled' | 'disabled';
/**
 * Wallet address of the account owner
 */
export type Wallet = string;
/**
 * Number of orders cancelled
 */
export type OrdersCancelled = number;
/**
 * Result of the operation
 */
export type Result = string;
/**
 * Number of subaccounts affected
 */
export type SubaccountsAffected = number;

export interface PublicChangeComplianceStatusJSONRPCSchema {
  request: PublicChangeComplianceStatusRequestSchema;
  response: PublicChangeComplianceStatusResponseSchema;
}
export interface PublicChangeComplianceStatusRequestSchema {
  id?: string | number;
  method: Method;
  params: PublicChangeComplianceStatusParamsSchema;
}
export interface PublicChangeComplianceStatusParamsSchema {
  status: Status;
  wallet: Wallet;
}
export interface PublicChangeComplianceStatusResponseSchema {
  id: string | number;
  result: PublicChangeComplianceStatusResultSchema;
}
export interface PublicChangeComplianceStatusResultSchema {
  orders_cancelled?: OrdersCancelled;
  result: Result;
  subaccounts_affected?: SubaccountsAffected;
}
