/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Get spot feed history by currency
 */
export type PublicGetSpotFeedHistory = PublicGetSpotFeedHistoryJSONRPCSchema;
export type Method = "public/get_spot_feed_history";
/**
 * Currency
 */
export type Currency = string;
/**
 * End timestamp
 */
export type EndTimestamp = number;
/**
 * Period
 */
export type Period = number;
/**
 * Start timestamp
 */
export type StartTimestamp = number;
/**
 * Currency
 */
export type Currency1 = string;
/**
 * Confidence score of the spot price
 */
export type Confidence = string;
/**
 * Spot price
 */
export type Price = string;
/**
 * Timestamp of when the spot price was recored into the database
 */
export type Timestamp = number;
/**
 * Timestamp bucket; this value is regularly spaced out with `period` seconds between data points, missing values are forward-filled from earlier data where possible, if no earlier data is available, values are back-filled from the first observed data point
 */
export type TimestampBucket = number;
/**
 * Spot feed history
 */
export type SpotFeedHistory = SpotFeedHistoryResponseSchema[];

export interface PublicGetSpotFeedHistoryJSONRPCSchema {
  request: PublicGetSpotFeedHistoryRequestSchema;
  response: PublicGetSpotFeedHistoryResponseSchema;
}
export interface PublicGetSpotFeedHistoryRequestSchema {
  id?: string | number;
  method: Method;
  params: PublicGetSpotFeedHistoryParamsSchema;
}
export interface PublicGetSpotFeedHistoryParamsSchema {
  currency: Currency;
  end_timestamp: EndTimestamp;
  period: Period;
  start_timestamp: StartTimestamp;
}
export interface PublicGetSpotFeedHistoryResponseSchema {
  id: string | number;
  result: PublicGetSpotFeedHistoryResultSchema;
}
export interface PublicGetSpotFeedHistoryResultSchema {
  currency: Currency1;
  spot_feed_history: SpotFeedHistory;
}
export interface SpotFeedHistoryResponseSchema {
  confidence: Confidence;
  price: Price;
  timestamp: Timestamp;
  timestamp_bucket: TimestampBucket;
}
