/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Get all active instruments for a given `currency` and `type`
 */
export type PublicGetInstruments = PublicGetInstrumentsJSONRPCSchema;
export type Method = "public/get_instruments";
/**
 * Underlying currency of asset (`ETH`, `BTC`, etc)
 */
export type Currency = string;
/**
 * If `True`: include expired assets
 */
export type Expired = boolean;
/**
 * `erc20`, `option`, or `perp`
 */
export type InstrumentType = "erc20" | "option" | "perp";
/**
 * Minimum valid increment of order amount
 */
export type AmountStep = string;
/**
 * Blockchain address of the base asset
 */
export type BaseAssetAddress = string;
/**
 * Sub ID of the specific base asset as defined in Asset.sol
 */
export type BaseAssetSubId = string;
/**
 * Underlying currency of base asset (`ETH`, `BTC`, etc)
 */
export type BaseCurrency = string;
/**
 * Instrument name
 */
export type InstrumentName = string;
/**
 * `erc20`, `option`, or `perp`
 */
export type InstrumentType1 = "erc20" | "option" | "perp";
/**
 * If `True`: instrument is tradeable within `activation` and `deactivation` timestamps
 */
export type IsActive = boolean;
/**
 * Percent of spot price fee rate for makers
 */
export type MakerFeeRate = string;
/**
 * Percent of option price fee cap, e.g. 12.5%, null if not applicable
 */
export type MarkPriceFeeRateCap = string | null;
/**
 * Maximum valid amount of contracts / tokens per trade
 */
export type MaximumAmount = string;
/**
 * Minimum valid amount of contracts / tokens per trade
 */
export type MinimumAmount = string;
/**
 * Unix timestamp of expiry date (in seconds)
 */
export type Expiry = number;
/**
 * Underlying settlement price index
 */
export type Index = string;
export type OptionType = "C" | "P";
/**
 * Settlement price of the option
 */
export type SettlementPrice = string | null;
export type Strike = string;
/**
 * Latest aggregated funding as per `PerpAsset.sol`
 */
export type AggregateFunding = string;
/**
 * Current hourly funding rate as per `PerpAsset.sol`
 */
export type FundingRate = string;
/**
 * Underlying spot price index for funding rate
 */
export type Index1 = string;
/**
 * Max rate per hour as per `PerpAsset.sol`
 */
export type MaxRatePerHour = string;
/**
 * Min rate per hour as per `PerpAsset.sol`
 */
export type MinRatePerHour = string;
/**
 * Static interest rate as per `PerpAsset.sol`
 */
export type StaticInterestRate = string;
/**
 * Quote currency (`USD` for perps, `USDC` for options)
 */
export type QuoteCurrency = string;
/**
 * Timestamp at which became or will become active (if applicable)
 */
export type ScheduledActivation = number;
/**
 * Scheduled deactivation time for instrument (if applicable)
 */
export type ScheduledDeactivation = number;
/**
 * Percent of spot price fee rate for takers
 */
export type TakerFeeRate = string;
/**
 * Tick size of the instrument, i.e. minimum price increment
 */
export type TickSize = string;
export type Result = InstrumentPublicResponseSchema[];

export interface PublicGetInstrumentsJSONRPCSchema {
  request: PublicGetInstrumentsRequestSchema;
  response: PublicGetInstrumentsResponseSchema;
}
export interface PublicGetInstrumentsRequestSchema {
  id?: string | number;
  method: Method;
  params: PublicGetInstrumentsParamsSchema;
}
export interface PublicGetInstrumentsParamsSchema {
  currency: Currency;
  expired: Expired;
  instrument_type: InstrumentType;
}
export interface PublicGetInstrumentsResponseSchema {
  id: string | number;
  result: Result;
}
export interface InstrumentPublicResponseSchema {
  amount_step: AmountStep;
  base_asset_address: BaseAssetAddress;
  base_asset_sub_id: BaseAssetSubId;
  base_currency: BaseCurrency;
  instrument_name: InstrumentName;
  instrument_type: InstrumentType1;
  is_active: IsActive;
  maker_fee_rate: MakerFeeRate;
  mark_price_fee_rate_cap?: MarkPriceFeeRateCap;
  maximum_amount: MaximumAmount;
  minimum_amount: MinimumAmount;
  option_details: OptionPublicDetailsSchema;
  perp_details: PerpPublicDetailsSchema;
  quote_currency: QuoteCurrency;
  scheduled_activation: ScheduledActivation;
  scheduled_deactivation: ScheduledDeactivation;
  taker_fee_rate: TakerFeeRate;
  tick_size: TickSize;
}
/**
 * Details of the option asset (if applicable)
 */
export interface OptionPublicDetailsSchema {
  expiry: Expiry;
  index: Index;
  option_type: OptionType;
  settlement_price?: SettlementPrice;
  strike: Strike;
}
/**
 * Details of the perp asset (if applicable)
 */
export interface PerpPublicDetailsSchema {
  aggregate_funding: AggregateFunding;
  funding_rate: FundingRate;
  index: Index1;
  max_rate_per_hour: MaxRatePerHour;
  min_rate_per_hour: MinRatePerHour;
  static_interest_rate: StaticInterestRate;
}
